[package]
name = "benchmarks-game"
version = "0.1.0"
authors = ["Ilia Schelokov <thaumant@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "nbody"
harness = false